package handler

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"api/gen/db"
	"api/internal/httpapi/internal/entity"
	"api/internal/httpapi/internal/middleware"
	"api/internal/httpapi/internal/store"
)

// Healthz godoc
// @Summary      Health check
// @Description  Returns API health status
// @Tags         health
// @Produce      json
// @Success      200  {object}  entity.HealthResponse
// @Router       /healthz [get]
func (h *Handler) Healthz(w http.ResponseWriter, _ *http.Request) error {
	return h.response(w, entity.HealthResponse{Msg: "OK"}, http.StatusOK)
}

// ListStreams godoc
// @Summary      List streams
// @Description  Returns all streams
// @Tags         streams
// @Produce      json
// @Success      200  {array}   entity.Stream
// @Failure      500  {object}  entity.ErrorResponse
// @Router       /streams [get]
func (h *Handler) ListStreams(w http.ResponseWriter, r *http.Request) error {
	streams, err := h.stream.List(r.Context())
	if err != nil {
		return err
	}
	out, err := entity.StreamsFromDB(streams)
	if err != nil {
		return err
	}
	return h.response(w, out, http.StatusOK)
}

// CreateStream godoc
// @Summary      Create stream
// @Description  Creates a new stream. ID and key are generated by the server.
// @Tags         streams
// @Accept       json
// @Produce      json
// @Param        body  body      entity.CreateStreamRequest  true  "Stream payload"
// @Success      201   {object}  entity.StreamResponse
// @Failure      400   {object}  entity.ErrorResponse
// @Failure      409   {object}  entity.ErrorResponse
// @Failure      500   {object}  entity.ErrorResponse
// @Router       /streams [post]
func (h *Handler) CreateStream(w http.ResponseWriter, r *http.Request) error {
	body, ok := middleware.Body[entity.CreateStreamRequest](r)
	if !ok {
		return middleware.Internal("missing request body")
	}

	status, err := entity.ToDBStreamStatus(body.Status)
	if err != nil {
		return middleware.BadRequest(err.Error())
	}

	created, err := h.stream.Create(r.Context(), body.Name, status)
	if err != nil {
		if errors.Is(err, store.ErrConflict) {
			return err
		}
		return middleware.BadRequest(err.Error())
	}
	resp, err := entity.StreamResponseFromDB(created, h.cfg.IngressURL, h.cfg.PublicURL)
	if err != nil {
		return err
	}
	return h.response(w, resp, http.StatusCreated)
}

func (h *Handler) streamID(r *http.Request) (int32, error) {
	id, err := strconv.ParseInt(r.PathValue("id"), 10, 32)
	if err != nil {
		return 0, middleware.BadRequest("invalid stream id")
	}
	return int32(id), nil
}

// GetStream godoc
// @Summary      Get stream by ID
// @Description  Returns a single stream
// @Tags         streams
// @Produce      json
// @Param        id   path      int  true  "Stream ID"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Failure      500  {object}  entity.ErrorResponse
// @Router       /streams/{id} [get]
func (h *Handler) GetStream(w http.ResponseWriter, r *http.Request) error {
	id, err := h.streamID(r)
	if err != nil {
		return err
	}

	stream, err := h.stream.GetByID(r.Context(), id)
	if err != nil {
		return err
	}
	out, err := entity.StreamFromDB(stream)
	if err != nil {
		return err
	}
	return h.response(w, out, http.StatusOK)
}

// UpdateStream godoc
// @Summary      Update stream
// @Description  Updates stream name and/or status
// @Tags         streams
// @Accept       json
// @Produce      json
// @Param        id    path      int                        true  "Stream ID"
// @Param        body  body      entity.UpdateStreamRequest  true  "Stream payload"
// @Success      200   {object}  entity.Stream
// @Failure      400   {object}  entity.ErrorResponse
// @Failure      404   {object}  entity.ErrorResponse
// @Failure      500   {object}  entity.ErrorResponse
// @Router       /streams/{id} [put]
func (h *Handler) UpdateStream(w http.ResponseWriter, r *http.Request) error {
	id, err := h.streamID(r)
	if err != nil {
		return err
	}

	body, ok := middleware.Body[entity.UpdateStreamRequest](r)
	if !ok {
		return middleware.Internal("missing request body")
	}

	status, err := entity.ToDBStreamStatus(body.Status)
	if err != nil {
		return middleware.BadRequest(err.Error())
	}

	updated, err := h.stream.Update(r.Context(), id, body.Name, status)
	if err != nil {
		return err
	}
	out, err := entity.StreamFromDB(updated)
	if err != nil {
		return err
	}
	return h.response(w, out, http.StatusOK)
}

// DeleteStream godoc
// @Summary      Delete stream
// @Description  Deletes a stream by ID
// @Tags         streams
// @Param        id  path  int  true  "Stream ID"
// @Success      204
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Failure      500  {object}  entity.ErrorResponse
// @Router       /streams/{id} [delete]
func (h *Handler) DeleteStream(w http.ResponseWriter, r *http.Request) error {
	id, err := h.streamID(r)
	if err != nil {
		return err
	}

	if err := h.stream.Delete(r.Context(), id); err != nil {
		return err
	}
	w.WriteHeader(http.StatusNoContent)
	return nil
}

type streamStatusTransition func(context.Context, string) (db.Stream, error)

func (h *Handler) handleStreamStatusTransition(
	w http.ResponseWriter,
	r *http.Request,
	transition streamStatusTransition,
) error {
	key := r.PathValue("key")
	if key == "" {
		return middleware.BadRequest("stream key is required")
	}

	stream, err := transition(r.Context(), key)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return err
		}
		return middleware.BadRequest(err.Error())
	}
	out, err := entity.StreamFromDB(stream)
	if err != nil {
		return err
	}
	return h.response(w, out, http.StatusOK)
}

// ReadyStream godoc
// @Summary      Mark stream as ready
// @Description  Updates stream status to ready
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Router       /streams/{key}/ready [post]
func (h *Handler) ReadyStream(w http.ResponseWriter, r *http.Request) error {
	return h.handleStreamStatusTransition(w, r, h.stream.Ready)
}

// GoLiveStream godoc
// @Summary      Mark stream as live
// @Description  Updates stream status to live
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Router       /streams/{key}/go-live [post]
func (h *Handler) GoLiveStream(w http.ResponseWriter, r *http.Request) error {
	return h.handleStreamStatusTransition(w, r, h.stream.GoLive)
}

// PauseStream godoc
// @Summary      Pause stream
// @Description  Updates stream status to paused
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Router       /streams/{key}/pause [post]
func (h *Handler) PauseStream(w http.ResponseWriter, r *http.Request) error {
	return h.handleStreamStatusTransition(w, r, h.stream.Pause)
}

// ResumeStream godoc
// @Summary      Resume stream
// @Description  Updates stream status to live
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Router       /streams/{key}/resume [post]
func (h *Handler) ResumeStream(w http.ResponseWriter, r *http.Request) error {
	return h.handleStreamStatusTransition(w, r, h.stream.Resume)
}

// EndStream godoc
// @Summary      End stream
// @Description  Updates stream status to ended
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.Stream
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Router       /streams/{key}/end [post]
func (h *Handler) EndStream(w http.ResponseWriter, r *http.Request) error {
	return h.handleStreamStatusTransition(w, r, h.stream.End)
}

// GetIngressURL godoc
// @Summary      Get stream ingress URL
// @Description  Returns the ingress URL for a stream by key
// @Tags         streams
// @Produce      json
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {object}  entity.IngressURLResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Failure      500  {object}  entity.ErrorResponse
// @Router       /streams/{key}/ingress [get]
func (h *Handler) GetIngressURL(w http.ResponseWriter, r *http.Request) error {
	key := r.PathValue("key")
	if key == "" {
		return middleware.BadRequest("stream key is required")
	}

	stream, err := h.stream.GetByKey(r.Context(), key)
	if err != nil {
		return err
	}
	out, err := entity.StreamFromDB(stream)
	if err != nil {
		return err
	}
	return h.response(w, entity.IngressURLResponse{
		Key: out.Key,
		URL: entity.BuildIngressURL(h.cfg.IngressURL, out.Key),
	}, http.StatusOK)
}

// ServeABRHLS serves FFmpeg-generated ABR HLS (master.m3u8 + variant playlists/segments).
// @Summary      Serve ABR HLS
// @Description  Serves FFmpeg-generated ABR HLS (master.m3u8 + variant playlists/segments)
// @Tags         streams
// @Produce      video/mp2t
// @Produce      application/vnd.apple.mpegurl
// @Param        key  path  string  true  "Stream key (UUID)"
// @Success      200  {file}  video/mp2t
// @Success      200  {file}  application/vnd.apple.mpegurl
// @Failure      400  {object}  entity.ErrorResponse
// @Failure      404  {object}  entity.ErrorResponse
// @Failure      500  {object}  entity.ErrorResponse
// @Router       /hls/{key} [get]
func (h *Handler) ServeABRHLS(w http.ResponseWriter, r *http.Request) error {
	key := r.PathValue("key")
	if key == "" || strings.Contains(key, "..") || strings.Contains(key, "/") {
		return middleware.BadRequest("invalid stream key")
	}

	if _, err := h.stream.GetByKey(r.Context(), key); err != nil {
		return err
	}

	// chi wildcard: /hls/{key}/* → PathValue("*")
	rel := filepath.Clean("/" + r.PathValue("*"))
	rel = strings.TrimPrefix(rel, "/")
	if rel == "" || rel == "." || strings.HasPrefix(rel, "..") {
		return middleware.BadRequest("invalid playlist path")
	}

	root := filepath.Clean(h.cfg.HLSAbrDir)
	full := filepath.Join(root, key, rel)
	log.Println(full)
	if !strings.HasPrefix(full, filepath.Join(root, key)+string(filepath.Separator)) &&
		full != filepath.Join(root, key) {
		return middleware.BadRequest("invalid playlist path")
	}

	if _, err := os.Stat(full); err != nil {
		if os.IsNotExist(err) {
			w.Header().Set("Access-Control-Allow-Origin", "*")
			w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
			ext := strings.ToLower(filepath.Ext(full))
			// Deleted/expired media segments are normal for a live sliding window.
			if ext == ".ts" {
				return middleware.NotFound("segment no longer in live window")
			}
			w.Header().Set("Retry-After", "2")
			return middleware.ServiceUnavailable("ABR playlist not ready yet; retry shortly")
		}
		return err
	}

	ext := strings.ToLower(filepath.Ext(full))
	w.Header().Set("Access-Control-Allow-Origin", "*")
	switch ext {
	case ".m3u8":
		// Serve playlist bytes directly so ServeFile cannot answer 304 against a
		// stale ETag/Last-Modified — that stalls live players until a hard refresh.
		data, err := os.ReadFile(full)
		if err != nil {
			if os.IsNotExist(err) {
				w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
				w.Header().Set("Retry-After", "2")
				return middleware.ServiceUnavailable("ABR playlist not ready yet; retry shortly")
			}
			return err
		}
		w.Header().Set("Content-Type", "application/vnd.apple.mpegurl")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		w.Header().Set("Pragma", "no-cache")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(data)
		return nil
	case ".ts":
		w.Header().Set("Content-Type", "video/mp2t")
		w.Header().Set("Cache-Control", "public, max-age=10")
	}
	http.ServeFile(w, r, full)
	return nil
}
